name: CI .NET Windows Service

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on'
        required: true
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.3.3
      with:
        versionSpec: '6.x'
    - name: Update AssemblyInfo
      uses: gittools/actions/gitversion/execute@v4.3.3
      with:
        updateAssemblyInfo: true
        updateAssemblyInfoFilename: src/ServiceControl_Exporter/ServiceControl_Exporter/Properties/AssemblyInfo.cs
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/ServiceControl_Exporter
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/ServiceControl_Exporter
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/ServiceControl_Exporter
    - name: Publish
      run: dotnet publish ServiceControl_Exporter/ServiceControl_Exporter.csproj -o artifacts 
      working-directory: src/ServiceControl_Exporter
    - name: Artifacts
      uses: actions/upload-artifact@v7.0.0
      with:
        name: artifacts
        path: src/ServiceControl_Exporter/artifacts/**/*


