name: CI .NET Windows Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '5.x'        
    - name: Update AssemblyInfo
      uses: gittools/actions/gitversion/execute@v3.0.0  
      with:
        useConfigFile: true
        updateAssemblyInfo: true
        updateAssemblyInfoFilename: src/ServiceControl_Exporter/ServiceControl_Exporter/Properties/AssemblyInfo.cs
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/ServiceControl_Exporter
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/ServiceControl_Exporter
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/ServiceControl_Exporter
    - name: Publish
      run: dotnet publish ServiceControl_Exporter/ServiceControl_Exporter.csproj -o artifacts 
      working-directory: src/ServiceControl_Exporter
    - name: Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: artifacts
        path: src/ServiceControl_Exporter/artifacts/**/*
