name: Release .NET Windows Service

on:
  push:
    tags:
    - '*.*.*'
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'        
    - name: Update AssemblyInfo
      uses: gittools/actions/gitversion/execute@v1.1.1  
      with:
        useConfigFile: true
        updateAssemblyInfo: true
        updateAssemblyInfoFilename: src/ServiceControl_Exporter/ServiceControl_Exporter/Properties/AssemblyInfo.cs
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/ServiceControl_Exporter
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/ServiceControl_Exporter
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/ServiceControl_Exporter
    - name: Publish
      run: dotnet publish ServiceControl_Exporter/ServiceControl_Exporter.csproj -o artifacts 
      working-directory: src/ServiceControl_Exporter
    - name: Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: artifacts
        path: src/ServiceControl_Exporter/artifacts/**/*
        
  metadata:
    name: Publish Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: artifacts

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Zip output
      run: zip -qq -r ../ServiceControl_Exporter_${{ steps.vars.outputs.tag }}.zip *
      working-directory: artifacts

    - uses: ncipollo/release-action@v1
      with:
        artifacts: ServiceControl_Exporter_${{ steps.vars.outputs.tag }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
